services:
  dev_container:
    build:
      context: /media/IDATA_LINUX/GIT/LOCAL/ai_cli/docker
      dockerfile: /media/IDATA_LINUX/GIT/LOCAL/ai_cli/docker/Dockerfile
    image: saicli  # common image name for all projects
    container_name: saicli__ai_codec64  # for now allow only 1 per project
    hostname: saicli__ai_codec64
    ports:
      - "${UI_EXT_PORT}:${UI_INT_PORT}"
    entrypoint: []
    command: sleep infinity
    init: true  # wrapper because 'sleep' does not handle SIGTERM
    volumes:  # '.' is relative to the 1st compose file in dockerComposeFile
      - ..:/workspaces
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.local/share/saicli/_data/common_auth/codex_auth.json:/home/admin/.codex/auth.json
      - home:/home/admin

volumes:
  home:
