cwd: ..  # or ../subproject1 . '.' is relative to 1st config file (probably this file)
workspaces:
  - name: Shells
    tabs:
      # --------- shell commands ----------------
      - label: misc
        panes:
          - command: ll
      # - label: make
      #   panes:
      #     - command: make test
      #       lf: false
      #       split: down

      # --------- dev servers -------------------
      - label: dev_servers
        panes:
          - command: m start-dev


# This is similar to tmux commands:
# tmux new-session \; \
#   send-keys 'codex' \; \
#   split-window -v \; \
#   send-keys 'codex -p high' \; \
#   split-window -v \; \
#   send-keys 'll' C-m \; \
#   select-pane -t 1
